articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('create-post/', views.create_post, name='create-post'),
    path('create-author/', views.create_author, name='create-author'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_detail, name='detail'),
    path('category/<str:category>/', views.article_by_category, name='category')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from articles.views import home




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('articles/', include('articles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.utils.text import slugify
from django import forms
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    short_content = models.TextField()
    long_content = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    image = models.ImageField(upload_to='article_images/')
    slug = models.SlugField(unique=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


    def get_detail_url(self):
        return reverse(
            'articles:detail',
            kwargs={
                'year': self.created_at.year,
                'month': self.created_at.month,
                'day': self.created_at.day,
                'slug': self.slug,
            })



class Comment(models.Model):
     post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
     name = models.CharField(max_length=80)
     email = models.EmailField()
     comment = models.TextField()
     created = models.DateTimeField(auto_now_add=True)



     class Meta:
         ordering = ['created']
         indexes = [
         models.Index(fields=['created']),
     ]

class CommentForm(forms.ModelForm):
     class Meta:
         model = Comment
         fields = ['name', 'email', 'comment']

     def __str__(self):
         return f'Comment by {self.name} on {self.post}'

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Author
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from .models import CommentForm



def home(request):
    posts = Post.objects.all()
    ctx = {'posts': posts}
    return render(request, 'index.html', ctx)

def create_post(request):
    if request.method =='POST':
        title = request.POST.get('title')
        category = request.POST.get('category')
        short_content = request.POST.get('short_content')
        long_content = request.POST.get('long_content')
        author_id = request.POST.get('author')
        image = request.FILES.get('image')

        if title and category and  short_content and long_content and author_id and image:
            author = Author.objects.get(id=author_id)
            Post.objects.create(
                title=title,
                category=category,
                short_content=short_content,
                long_content=long_content,
                author=author,
                image=image
            )
            return redirect('home')
    authors = Author.objects.all()
    ctx = {'authors': authors}
    return render(request, 'articles/create-article.html', ctx)


def create_author(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        bio = request.POST.get('bio')
        email = request.POST.get('email')

        if name and bio and email:
            Author.objects.create(
                name=name,
                bio=bio,
                email=email
            )
            return redirect('home')
    return render(request, 'articles/create-author.html')


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect(post.get_detail_url())


    ctx = {'post': post, 'form': form}
    return render(request, 'articles/blog-detail.html', ctx)


def article_by_category(request, category):
    posts = Post.objects.filter(category=category)
    ctx = {'posts': posts, 'category': category}
    return render(request, 'articles/articles-by-category.html', ctx)




def post_detail(request, year, month, day, slug):
    post = get_object_or_404(
        Post,
        slug=slug,
        created_at__year=year,
        created_at__month=month,
        created_at__day=day,
    )
    related_posts = Post.objects.filter(category=post.category).exclude(id=post.id)[:3]

    ctx = {'post': post,
           'related_posts': related_posts,
           }
    return render(request, 'articles/blog-detail.html', ctx)

templates/articles/articles-by-category.html
{% extends 'base.html' %}

{% block title %}{{ category|title }} - Zamonaviy Dasturchi{% endblock %}

{% block content %}
    <h1>{{ category|title }} Maqolalar</h1>

    {% if posts %}
        <div class="category-posts">
            {% for post in posts %}
                <article class="post">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image" width="500" height="300">
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.short_content }}</p>
                    <a href="{{ post.get_detail_url }}" class="read-more">Batafsil o'qish</a>
                </article>
            {% empty %}
                <h3>Hozircha maqola yo`q</h3>
            {% endfor %}
        </div>
    {% else %}
        <p>Bu kategoriyada hech qanday maqola mavjud emas.</p>
    {% endif %}
{% endblock %}

templates/articles/blog-detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} - Zamonaviy Dasturchi{% endblock %}

{% block content %}
    <article class="post-content">
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
        <div class="post-meta">
            <span>Muallif: {{ post.author.name }}</span>
            <span>Sana: {{ post.created_at }}</span>
        </div>
        <h1>{{ post.title }}</h1>
        <p>{{ post.long_content }}</p>
    </article>

    <section class="comments">
        <h2>Izohlar</h2>
        {% for comment in post.comments.all %}
            <div class="comment">
                <h3>{{ comment.name }}</h3>
                <p>{{ comment.comment }}</p>
                <small>{{ comment.created }}</small>
            </div>
        {% empty %}
            <p>Hozircha izohlar mavjud emas.</p>
        {% endfor %}
    </section>

    <section class="comment-form-section">
        <h3>Izoh qoldirish</h3>
        <form action="{% url 'articles:post_comment' post.id %}" method="post">
             {{ form.as_p }}
             {% csrf_token %}
         <p><input type="submit" value="Izoh qo`shish"></p>
        </form>
    </section>

    <h2>O'xshash Maqolalar</h2>
    <section class="related-posts">
        {% for related_post in related_posts %}
            <div class="related-post">
                <img src="{{ related_post.image.url }}" alt="{{ related_post.title }}">
                <h3>{{ related_post.title }}</h3>
            </div>
        {% endfor %}
    </section>

{% endblock %}

templates/articles/create-article.html
{% extends 'base.html' %}

{% block title %}Yangi Maqola Qo'shish - Zamonaviy Dasturchi{% endblock %}

{% block content %}
    <section class="create-article-form">
                <h2>Yangi Maqola Qo'shish</h2>
                <form action="{% url 'articles:create-post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">Sarlavha:</label>
                        <input type="text" id="title" name="title" required>
                    </div>
                    <div class="form-group">
                    <label for="category">Kategoriya:</label>
                    <select id="category" name="category" required>
                        <option value="">Kategoriya tanlang:</option>
                        <option value="web developing">Web Dasturlash</option>
                        <option value="mobile developing">Mobil Dasturlash</option>
                        <option value="ai ml">AI va ML</option>
                        <option value="life of programmers">Dasturchilar hayoti</option>
                    </select>
                    </div>
                    <div class="form-group">
                        <label for="short_content">Qisqa mazmuni:</label>
                        <textarea id="short_content" name="short_content" required></textarea>
                    </div>
                    <div class="form-group">
                    <label for="long_content">Maqola matni:</label>
                    <textarea id="long_content" name="long_content" rows="10" required placeholder="Full article content"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="author">Muallif:</label>
                        <select id="author" name="author" required>
                            <option value="">Muallifni tanlang</option>
                            {% for author in authors %}
                                <option value="{{ author.id }}">{{ author.name }}</option>
                            {% empty %}
                            <option value="">Hozircha mualliflar yo`q</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="image">Rasm:</label>
                        <input type="file" id="image" name="image" accept="image/*" required>
                    </div>
                    <button type="submit" class="submit-button">Maqolani Qo'shish</button>
                </form>
            </section>
{% endblock %}

templates/articles/create-author.html
{% extends 'base.html' %}

{% block title %}Yangi Muallif Qo'shish - Zamonaviy Dasturchi{% endblock %}

{% block content %}
    <section class="create-author-form">
                <h2>Yangi Muallif Qo'shish</h2>
                <form action="{% url 'articles:create-author' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Ism:</label>
                        <input type="text" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="bio">Biografiya:</label>
                        <textarea id="bio" name="bio" required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" id="email" name="email" required>
                    </div>
                    <button type="submit" class="submit-button">Muallifni Qo'shish</button>
                </form>
            </section>
{% endblock %}

templates/articles/success-commented.html
{% extends 'base.html' %}


{% block title %}Izoh muvaffaqiyatli qoldirildi - Zamonaviy Dasturchi{% endblock %}


{% block content %}
    <div class="success-message">
        <div class="success-icon">✅</div>
        <h1>Izohingiz muvaffaqiyatli qoldirildi!</h1>
        <p>Rahmat! Sizning fikringiz biz uchun muhim.</p>
        <a href="{{ post.get_detail_url }}" class="button">Maqolaga qaytish</a>
        <a href="{% url 'home' %}" class="button">Asosiy sahifaga o'tish</a>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="page-container">
    <div class="content-wrap">
        {# HEADER #}
       {% include 'includes/header.html' %}

        {# NAVBAR #}
        {% include 'includes/navbar.html' %}

        <main>
            {% block content %}{% endblock %}
        </main>
    </div>

    {# FOOTER #}
    {% include 'includes/footer.html' %}

    <button id="mode-toggle">Tungi rejim</button>

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/includes/footer.html
<footer>
    <p>&copy; 2023 Zamonaviy Dasturchi. Barcha huquqlar himoyalangan.</p>
</footer>

templates/includes/header.html
<header>
    <h1>Zamonaviy Dasturchi</h1>
</header>

templates/includes/navbar.html
<nav>
    <a href="{% url 'home' %}">Asosiy</a>
    <a href="{% url 'articles:category' category='web developing' %}">Web Dasturlash</a>
    <a href="{% url 'articles:category' category='mobile developing' %}">Mobil Dasturlash</a>
    <a href="{% url 'articles:category' category='ai ml' %}">AI va ML</a>
    <a href="{% url 'articles:category' category='life of programmers' %}">Dasturchilar hayoti</a>
    <a href="{% url 'articles:create-author' %}">Yangi Muallif Qo'shish</a>
    <a href="{% url 'articles:create-post' %}">Yangi Maqola Qo'shish</a>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}Zamonaviy Dasturchi{% endblock %}

{% block content %}
    {% for post in posts %}
        <article class="post">
            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image" width="500" height="300">
            <h2>{{ post.title }}</h2>
            <p>{{ post.short_content }}</p>
            <a href="{{ post.get_detail_url }}" class="read-more">Batafsil o'qish</a>
        </article>
    {% empty %}
        <h3>Hozircha maqola yo`q</h3>
    {% endfor %}
{% endblock %}